name: CI
on:
  push:
    branches: [main]
    tags-ignore: [v*]
  pull_request:
    branches: [main]
env:
  PUPPETEER_SKIP_DOWNLOAD: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Lint files
        run: bun lint
      - name: Typecheck
        run: bun typecheck
      - name: Build
        id: build
        run: bun run icons:build
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: font
          path: ./dist
