name: Generate Previews
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "icons/**"
      - scripts/icons/preview.ts
      - scripts/catwalk.ts
    tags-ignore: [v*]
jobs:
  generate-previews:
    name: Generate Previews
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/bun@v1
      - name: Setup catppuccin/catwalk
        uses: catppuccin/setup-catwalk@v1.0.0
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Generate Previews
        run: bun previews
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: re-generate previews"
          commit-message: "chore: re-generate previews"
          branch: chore/re-generate-previews
          delete-branch: true
          add-paths: |
            assets/*
